# import data
hotel_bookings <- read.csv("hotel_bookings.csv")
str(hotel_bookings)
# check that we have ggplot2 installed (and yes)
library()
# but refuses to load, refresh tidyverse and worked
library(tidyverse)

#find date boundaries
min_year <- min(hotel_bookings$arrival_date_year)
max_year <- max(hotel_bookings$arrival_date_year)

ggplot(data = hotel_bookings) + 
  geom_bar(mapping = aes(x = market_segment)) +
  facet_wrap(~hotel) +
  theme(axis.text.x = element_text(angle = 45)) +
  labs(title = "City Hotel vs Resort Hotel Market Segments bookings",
       caption = paste0("Data from ", min_year, " to ", max_year),
       x = "Market Segment", y = "Number of Bookings")

ggsave('hotel_bookings.jpg', width = 7, height = 7, units = "in")


############## OUTPUT ###################
#> str(hotel_bookings)
#'data.frame':	119390 obs. of  32 variables:
#  $ hotel                         : chr  "Resort Hotel" "Resort Hotel" "Resort Hotel" "Resort Hotel" ...
#$ is_canceled                   : int  0 0 0 0 0 0 0 0 1 1 ...
#$ lead_time                     : int  342 737 7 13 14 14 0 9 85 75 ...
#$ arrival_date_year             : int  2015 2015 2015 2015 2015 2015 2015 2015 2015 2015 ...
#$ arrival_date_month            : chr  "July" "July" "July" "July" ...
#$ arrival_date_week_number      : int  27 27 27 27 27 27 27 27 27 27 ...
#$ arrival_date_day_of_month     : int  1 1 1 1 1 1 1 1 1 1 ...
#$ stays_in_weekend_nights       : int  0 0 0 0 0 0 0 0 0 0 ...
#$ stays_in_week_nights          : int  0 0 1 1 2 2 2 2 3 3 ...
#$ adults                        : int  2 2 1 1 2 2 2 2 2 2 ...
#$ children                      : int  0 0 0 0 0 0 0 0 0 0 ...
#$ babies                        : int  0 0 0 0 0 0 0 0 0 0 ...
#$ meal                          : chr  "BB" "BB" "BB" "BB" ...
#$ country                       : chr  "PRT" "PRT" "GBR" "GBR" ...
#$ market_segment                : chr  "Direct" "Direct" "Direct" "Corporate" ...
#$ distribution_channel          : chr  "Direct" "Direct" "Direct" "Corporate" ...
#$ is_repeated_guest             : int  0 0 0 0 0 0 0 0 0 0 ...
#$ previous_cancellations        : int  0 0 0 0 0 0 0 0 0 0 ...
#$ previous_bookings_not_canceled: int  0 0 0 0 0 0 0 0 0 0 ...
#$ reserved_room_type            : chr  "C" "C" "A" "A" ...
#$ assigned_room_type            : chr  "C" "C" "C" "A" ...
#$ booking_changes               : int  3 4 0 0 0 0 0 0 0 0 ...
#$ deposit_type                  : chr  "No Deposit" "No Deposit" "No Deposit" "No Deposit" ...
#$ agent                         : chr  "NULL" "NULL" "NULL" "304" ...
#$ company                       : chr  "NULL" "NULL" "NULL" "NULL" ...
#$ days_in_waiting_list          : int  0 0 0 0 0 0 0 0 0 0 ...
#$ customer_type                 : chr  "Transient" "Transient" "Transient" "Transient" ...
#$ adr                           : num  0 0 75 75 98 ...
#$ required_car_parking_spaces   : int  0 0 0 0 0 0 0 0 0 0 ...
#$ total_of_special_requests     : int  0 0 0 0 1 1 0 1 1 0 ...
#$ reservation_status            : chr  "Check-Out" "Check-Out" "Check-Out" "Check-Out" ...
#$ reservation_status_date       : chr  "2015-07-01" "2015-07-01" "2015-07-02" "2015-07-02" ...

#>min(hotel_bookings$arrival_date_year)
#[1] 2015
#> max(hotel_bookings$arrival_date_year)
#[1] 2017